// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cxxtitable
List cxxtitable(SEXP sig);
RcppExport SEXP smash_cxxtitable(SEXP sigSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP );
        List __result = cxxtitable(sig);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cxxtirtable
NumericMatrix cxxtirtable(SEXP sig);
RcppExport SEXP smash_cxxtirtable(SEXP sigSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP );
        NumericMatrix __result = cxxtirtable(sig);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cxxreverse_gwave
NumericVector cxxreverse_gwave(SEXP estimate, SEXP pmat, SEXP qmat);
RcppExport SEXP smash_cxxreverse_gwave(SEXP estimateSEXP, SEXP pmatSEXP, SEXP qmatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type estimate(estimateSEXP );
        Rcpp::traits::input_parameter< SEXP >::type pmat(pmatSEXP );
        Rcpp::traits::input_parameter< SEXP >::type qmat(qmatSEXP );
        NumericVector __result = cxxreverse_gwave(estimate, pmat, qmat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cxxreverse_gvwave
NumericVector cxxreverse_gvwave(SEXP estimate, SEXP pmat, SEXP qmat);
RcppExport SEXP smash_cxxreverse_gvwave(SEXP estimateSEXP, SEXP pmatSEXP, SEXP qmatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type estimate(estimateSEXP );
        Rcpp::traits::input_parameter< SEXP >::type pmat(pmatSEXP );
        Rcpp::traits::input_parameter< SEXP >::type qmat(qmatSEXP );
        NumericVector __result = cxxreverse_gvwave(estimate, pmat, qmat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cxxSParentTItable
NumericVector cxxSParentTItable(SEXP sig);
RcppExport SEXP smash_cxxSParentTItable(SEXP sigSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP );
        NumericVector __result = cxxSParentTItable(sig);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cxxreverse_pwave
NumericVector cxxreverse_pwave(SEXP estimate, SEXP pmat, SEXP qmat);
RcppExport SEXP smash_cxxreverse_pwave(SEXP estimateSEXP, SEXP pmatSEXP, SEXP qmatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type estimate(estimateSEXP );
        Rcpp::traits::input_parameter< SEXP >::type pmat(pmatSEXP );
        Rcpp::traits::input_parameter< SEXP >::type qmat(qmatSEXP );
        NumericVector __result = cxxreverse_pwave(estimate, pmat, qmat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
