---
title: "Interactive plot for exploring results of Gaussian mean estimation experiments"
runtime: shiny
output: html_document
---

Below is a Shiny interactive plot that can be used to explore the
results of the Gaussian mean estimation simulation study. In this
simulation study, the signal denoising methods were compared in
simulated data sets generated with a variety of mean and variance
functions, and with different signal-to-noise ratios. For more
details, including instructions for re-running these experiments, see
the README in the "dsc" directory of the git repository.

See the text below for more details on how to interpret these results.

```{r create-shiny-plot, echo=FALSE, message=FALSE, warning=FALSE}
# Load the packages.
library(dplyr)
library(ggplot2)
library(cowplot)
library(rmarkdown)
library(shiny)

# Load the results of the simulation experiments.
load("../output/dscr.RData")

# Set up the Shiny plot.
scenario_names = as.character(unique(res$scenario))
method_names = as.character(unique(res$method))

# Render the webpage with the interactive plot.
renderPlot({
  res.filter = filter(res,scenario %in% input$scen.subset &
                          method %in% input$method.subset)
  print(input)
  res.filter$value = res.filter[["mise"]]
  ggplot(res.filter,aes(x = method,y = value)) +
    geom_boxplot() +
    facet_grid(.~ scenario) +
    labs(y = "error (MISE)") +
    theme(axis.text.x = element_text(angle = 45,hjust = 1),
	      axis.line = element_blank())
})
inputPanel(
  checkboxGroupInput("scen.subset","scenario",choices = scenario_names,
                     selected = "sp.1.v2"),
  checkboxGroupInput("method.subset","method",choices = method_names,
                     selected = method_names))
```

The boxplots above summarize the error (specifically, mean of the
integrated squared errors, or MISE) in the mean estimate when applying
different methods in to different simulation scenarios.

Each simulation scenario corresponds to a combination of a mean
function, variance function, and signal-to-noise function used to
simulated the Gaussian-distributed data. In the Shiny plot above, a
scenario is labeled as "mean.SNR.variance", in which "mean",
"variance" and "SNR" refer to the mean function, variance function and
signal-to-noise ratio. See [here](gaussian_signal.html) for plots of
the mean and variance functions.

These are the different mean functions we used in the simulations:

1. Spikes (sp)
2. Bumps (bump)
3. Blocks (blk)
4. Angles (ang)
5. Doppler (dop)
6. Blip (blip)
7. Corner (cor)

And these are the variance functions we used:

1. Constant function (v1)
2. Triple exponential (v2)
3. Doppler (v3)
4. Bumps (v4)
5. Clipped Blocks (v5)

We used signal-to-noise ratios of 1 and 3.

These are the methods we compared:

EbayesThresh (ebayesthresh)
BAMS (bams)
BlockJS - blockjs 
Neighblock (neighblock)
SureShrink (sure)
Bayesian Posterior Mean (postmean)
TI thresholding (tithresh)
SMASH (smash)

Most of  these methods assume homoskedastic noise, and use the
Symm8 basis by default. TI thresholding was run with both the
homoskedastic ("tithresh.homo") using the Symm8 (.s8) basis, as well as
with variance estimated variance using either RMAD ("tithresh.rmad") or SMASH
("tithresh.smash"). TI thresholding was also run with the true
variance provided ("tithresh.true").

As for SMASH, we ran this method with the homoskedatic assumption
("smash.homo"), and when the variance was estimated. For variance
estimation in SMASH, we compared two approaches: JASH ("smash.jash")
and the ASH-based procedure ("smash.haar" and" smash.s8" for the two
different bases). We also evaluated SMASH when it was provided with
the ground-truth variance.
