# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxtitable <- function(sig) {
    .Call('smash_cxxtitable', PACKAGE = 'smash', sig)
}

cxxtirtable <- function(sig) {
    .Call('smash_cxxtirtable', PACKAGE = 'smash', sig)
}

cxxreverse_gwave <- function(estimate, pmat, qmat) {
    .Call('smash_cxxreverse_gwave', PACKAGE = 'smash', estimate, pmat, qmat)
}

cxxreverse_gvwave <- function(estimate, pmat, qmat) {
    .Call('smash_cxxreverse_gvwave', PACKAGE = 'smash', estimate, pmat, qmat)
}

cxxSParentTItable <- function(sig) {
    .Call('smash_cxxSParentTItable', PACKAGE = 'smash', sig)
}

cxxreverse_pwave <- function(estimate, pmat, qmat) {
    .Call('smash_cxxreverse_pwave', PACKAGE = 'smash', estimate, pmat, qmat)
}

