---
title: "SMASH companion source code repository"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

This repository contains data and R source code accompanying our
manuscript,

> Zhengrong Xing, Peter Carbonetto and Matthew Stephens (2020).
> *Flexible signal denoising via flexible empirical Bayes shrinkage.*
> [arXiv:1605.07787][smash-preprint].

If you find any of the source code in this repository useful for your
work, please cite our paper.

The new methods can be found in the [smashr package][smashr].

## Contents

The following analyses generate some of the empirical results
presented in [Xing, Carbonetto & Stephens (2020)][smash-preprint]. If
you encounter a problem running any of the R code in these examples,
please post an [issue][issues].

### Illustration

+ [SMASH applied to the "Spikes" data set.](spikesdemo.html)

### Simulation experiments

1. [Estimating the mean function from Gaussian-distributed
data.](gaussmeanest.html)

2. [Plots of the mean and variance functions used to simulate Gaussian data for the mean estimation experiments.](gaussian_signals.html)

3. [Interactive ("Shiny") plot for exploring results of Gaussian mean estimation experiments.](gauss_shiny_setup.html)

4. [Estimating the variance function from Gaussian-distributed
data.](gaussvarest.html)

5. [Summary of results from Poisson simulations.](poisson.html)

### Illustrative applications

1. [Motorcycle acceleration data.](motorcycle.html)

2. [ChIP-seq data.](chipseq.html)

## What's included in the git repository

See [here][smash-github] for the source repository. This is the
overall structure of the repository:

```
├── analysis
├── code
├── data
├── docs
├── dsc
├── output
└── shiny
```

+ The `analysis` directory contains R Markdown source files for the
  workflowr website, including R code implementing the SMASH demos,
  and R code to generate tables and figures for the manuscript.

+ The `code` directory contains additional supporting code for the
  demos and analyses of the results.

+ The `data` directory contains data files used in the ChIP-seq demo.

+ The `docs` directory contains webpages generated from the R
  Markdown files in the analysis directory.

+ The `dsc` directory contains R and MATLAB code used to implement the
  "Gaussian mean estimation" simulations in the manuscript.

+ The `output` directory contains results from the Gaussian and
  Poisson simulations. The `pois_hf.RData` file in this directory
  contains results from experimenting with different Gaussian
  denoising techniques for the Haar-Fisz algorithm in the Poisson
  simulations.

+ The `shiny` directory contains code to generate the Shiny
  Web app in R.

## License

Copyright (c) 2016-2021, Zhengrong Xing, Peter Carbonetto & Matthew
Stephens.

Our numerical comparisons make use of some of the functions from
[WaveLab][wavelab], so we have included the WaveLab source code in
this repository. See the `COPYING.m` Wavelab850 subdirectory for more
information about distributing WaveLab.

Our numerical comparisons also use of some functions from
[GaussianWaveDen][waveden], so we have included the GaussianWaveDen
source in this repository. For information about distributing
GaussianWaveDen, see the `copyright.m` in the WavDen
subdirectory. Note that we made one small improvement to the code in
`blockJS.m` to prevent an error that occurs when running the code in
newer versions of MATLAB.

All other source code and software in this repository are made
available under the terms of the [MIT license][mit-license]. See the
`LICENSE` file in the git repository for the full text of the license.

## Credits

This project was developed by [Zhengrong Xing][zhengrong] at the
University of Chicago, with support and contributions from
[Peter Carbonetto][peter] and [Matthew Stephens][matthew].

[smash-github]: https://github.com/stephenslab/smash-paper
[smashr]: https://github.com/stephenslab/smashr
[smash-preprint]: https://arxiv.org/abs/1605.07787
[issues]: https://github.com/stephenslab/smash-paper/issues
[mit-license]: https://opensource.org/licenses/mit-license.html
[wavelab]: http://statweb.stanford.edu/~wavelab
[waveden]: http://www-ljk.imag.fr/SMS/software/GaussianWaveDen/down.html
[zhengrong]: https://github.com/zrxing
[peter]: http://pcarbo.github.io
[matthew]: http://stephenslab.uchicago.edu
